In [32]:
import pandas as pd
import numpy as np

##### ***For downloading a file use urlretrieve***

In [33]:
from urllib.request import urlretrieve

In [34]:
italy_covid_url = 'https://gist.githubusercontent.com/aakashns/f6a004fa20c84fec53262f9a8bfee775/raw/f309558b1cf5103424cef58e2ecb8704dcd4d74c/italy-covid-daywise.csv'

urlretrieve(italy_covid_url,'italy-covid-daywise.csv')

('italy-covid-daywise.csv', <http.client.HTTPMessage at 0x266881f3110>)

In [35]:
import matplotlib

In [36]:
import matplotlib.pyplot as plt

In [37]:
import seaborn as sns

In [38]:
covid_df = pd.read_csv('italy-covid-daywise.csv')

##### ***We use 'pd' as pandas function is being on that dataframe***

*The .read_csv is specifically for csv files to read and convert it to pandas dataframe*

In [39]:
type(covid_df)

pandas.core.frame.DataFrame

In [40]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

***dataframe.info() results column wise details such as datatype and count***

In [41]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    object
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), object(1)
memory usage: 7.9+ KB

In [42]:
covid_df.describe()

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

*Column property (arrtibute)of dataframe gives list of column in dataframe*

In [43]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [44]:
covid_df.shape

(248, 4)

*we can read multiple different format by using read.csv()*

In [45]:
#Pandas Dataframe is similar to this

covid_data_dict = {
    'date' : ['date1','date2','date3','date4','date5','date6',],
    'new_cases': [1444,1365,996,975,1326],
    'new_deaths' : [1,4,6,8,6],
    'new_tests' : [5443,653,2432,6342]
}

##### *Imagine this picture when ever you are going to use pandas_dataframe*

##### ***Retrive Data From Dataframe***

In [46]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [47]:
covid_df['new_cases']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

In [49]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [52]:
covid_df['new_tests']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
        ...
243    53541.0
244    42583.0
245    54395.0
246        NaN
247        NaN
Name: new_tests, Length: 248, dtype: float64

***Each Column is Represented by data structure called Series.***

In [50]:
type(covid_df['new_cases'])

pandas.core.series.Series

***We Can Access the value in particular column by using 2d array indexing methods***

In [51]:
covid_df['new_cases'][142]

665.0

*Pandas also provide the .at method to dirrectly retirve at specific row & column*

In [65]:
covid_df.at[142,'new_cases']

665.0

In [68]:
covid_df.new_cases

# Same as covid_df['new_cases']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

*We can access some particular columns by creating a dataframe of that particular columns*

In [69]:
cases_df = covid_df[['date','new_cases']]

In [70]:
cases_df

           date  new_cases
0    2019-12-31        0.0
1    2020-01-01        0.0
2    2020-01-02        0.0
3    2020-01-03        0.0
4    2020-01-04        0.0
..          ...        ...
243  2020-08-30     1444.0
244  2020-08-31     1365.0
245  2020-09-01      996.0
246  2020-09-02      975.0
247  2020-09-03     1326.0

[248 rows x 2 columns]

*All the accessing operation result a dataframe pointing to original dataframe so be cautions around using part of dataframe it can alter original dataframe*

*To Over come this situation we can use .copy() method to make a view of that particular columns of that dataframe*

In [72]:
cases_df2 = covid_df.copy()
cases_df2

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

##### *.loc[index] is used to retrive particular row or multiple rows from dataframe*

In [73]:
covid_df.loc[142]

date          2020-05-21
new_cases          665.0
new_deaths         161.0
new_tests        40644.0
Name: 142, dtype: object

*We Can view few rows from dataframe by using .head(no_of_rows) and .tail(no_of_rows)*

In [74]:
covid_df.head(5)

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

In [75]:
covid_df.tail(3)

           date  new_cases  new_deaths  new_tests
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

In [77]:
covid_df.at[0,'new_tests']

nan

Italy Started sharing new_tests data after 19th april 2020 till then 935310 test have conducted

*We can retrive the index of the row from where the number is started where before it the data is represented in form of NaN*

In [78]:
covid_df.new_tests.first_valid_index()

111

##### ***We Can Also use python slicing to slice between rows***

In [80]:
covid_df[45:89]

          date  new_cases  new_deaths  new_tests
45  2020-02-14        0.0         0.0        NaN
46  2020-02-15        0.0         0.0        NaN
47  2020-02-16        0.0         0.0        NaN
48  2020-02-17        0.0         0.0        NaN
49  2020-02-18        0.0         0.0        NaN
50  2020-02-19        0.0         0.0        NaN
51  2020-02-20        0.0         0.0        NaN
52  2020-02-21        0.0         0.0        NaN
53  2020-02-22       14.0         0.0        NaN
54  2020-02-23       62.0         2.0        NaN
55  2020-02-24       53.0         0.0        NaN
56  2020-02-25       97.0         4.0        NaN
57  2020-02-26       93.0         5.0        NaN
58  2020-02-27       78.0         1.0        NaN
59  2020-02-28      250.0         5.0        NaN
60  2020-02-29      238.0         4.0        NaN
61  2020-03-01      240.0         8.0        NaN
62  2020-03-02      561.0         6.0        NaN
63  2020-03-03      347.0        17.0        NaN
64  2020-03-04      466.0        28.0        NaN
65  2020-03-05      587.0        27.0        NaN
66  2020-03-06      769.0        41.0        NaN
67  2020-03-07      778.0        49.0        NaN
68  2020-03-08     1247.0        36.0        NaN
69  2020-03-09     1492.0       133.0        NaN
70  2020-03-10     1797.0        98.0        NaN
71  2020-03-11      977.0       167.0        NaN
72  2020-03-12     2313.0       196.0        NaN
73  2020-03-13     2651.0       189.0        NaN
74  2020-03-14     2547.0       252.0        NaN
75  2020-03-15     3497.0       173.0        NaN
76  2020-03-16     2823.0       370.0        NaN
77  2020-03-17     4000.0       347.0        NaN
78  2020-03-18     3526.0       347.0        NaN
79  2020-03-19     4207.0       473.0        NaN
80  2020-03-20     5322.0       429.0        NaN
81  2020-03-21     5986.0       625.0        NaN
82  2020-03-22     6557.0       795.0        NaN
83  2020-03-23     5560.0       649.0        NaN
84  2020-03-24     4789.0       601.0        NaN
85  2020-03-25     5249.0       743.0        NaN
86  2020-03-26     5210.0       685.0        NaN
87  2020-03-27     6153.0       660.0        NaN
88  2020-03-28     5959.0       971.0        NaN

In [81]:
covid_df.sample(25)

           date  new_cases  new_deaths  new_tests
165  2020-06-13      163.0        56.0    32880.0
57   2020-02-26       93.0         5.0        NaN
162  2020-06-10      283.0        79.0    37865.0
112  2020-04-21     2256.0       454.0    28095.0
71   2020-03-11      977.0       167.0        NaN
238  2020-08-25      953.0         4.0    45798.0
38   2020-02-07        0.0         0.0        NaN
59   2020-02-28      250.0         5.0        NaN
140  2020-05-19      451.0        99.0    40226.0
222  2020-08-09      347.0        13.0    22773.0
229  2020-08-16      629.0       158.0    22470.0
68   2020-03-08     1247.0        36.0        NaN
111  2020-04-20     3047.0       433.0     7841.0
81   2020-03-21     5986.0       625.0        NaN
1    2020-01-01        0.0         0.0        NaN
142  2020-05-21      665.0       161.0    40644.0
56   2020-02-25       97.0         4.0        NaN
216  2020-08-03      238.0         8.0    13467.0
201  2020-07-19      249.0        14.0    20621.0
90   2020-03-30     5217.0       758.0        NaN
158  2020-06-06      518.0        85.0    34036.0
240  2020-08-27     1366.0        13.0    57640.0
65   2020-03-05      587.0        27.0        NaN
39   2020-02-08        0.0         0.0        NaN
227  2020-08-14      522.0         6.0    24868.0

In [82]:
for x in covid_df['new_deaths']:
    if x == 0:
        x = "Zero"

In [86]:
covid_df[2]

KeyError: 2